version: '3'

services:
  react-app:	
    image: reactapp:latest	
    deploy:
      restart_policy:
        condition: "any"
        delay: "0"
        max_attempts: 3
        window: "30s"	
    ports: 	
      - 7070:7070	
    networks:	
      - proxy	
    labels:	
      - "traefik.enable=true"
      - "traefik.http.routers.reactapp.rule=Host(`react.turkiyeoku.com`)"
      - "traefik.http.routers.reactapp.entrypoints=https"
      - "traefik.http.routers.reactapp.tls.certresolver=http"

networks:
  proxy:
    external: true
